# Generated by Django 5.2.8 on 2025-12-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("bank", "Перевод на счёт")],
                max_length=20,
                null=True,
            ),
        ),
    ]
