# Generated by Django 5.2.8 on 2025-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_amount_alter_payment_pay_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма"
            ),
        ),
    ]
