# Generated by Django 5.2.8 on 2025-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
