# Generated by Django 5.2.8 on 2025-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью урока",
                null=True,
                upload_to="materials/previews",
                verbose_name="Превью урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
